---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.packer
    version: 1.0.2

# Tower automatically installs these collections when project syncs
collections:
  - name: amazon.aws
